[development]
address = "localhost"
port = 8000
workers = 8
log = "normal"
secret_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk="
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 80
workers = 8
log = "normal"
secret_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk="
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8000
workers = 8
log = "critical"
secret_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk="
limits = { forms = 32768 }
